services:
  gis-db:
    image: postgis/postgis:16-3.4
    container_name: custom_map_db
    environment:
      - POSTGRES_USER=map_admin
      - POSTGRES_PASSWORD=map_secure_pass
      - POSTGRES_DB=iran_map
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
    restart: always

  nominatim:
    image: mediagis/nominatim:4.4
    container_name: custom_nominatim
    ports:
      - "8080:8080" 
    volumes:
      - nominatim_data:/var/lib/postgresql/14/main
      - ./data:/data
    environment:
      - PBF_PATH=/data/iran-latest.osm.pbf 
      - NOMINATIM_DEFAULT_LANGUAGE=fa
    restart: always


volumes:
  postgres_data:
  nominatim_data: